title: SwitchedBit
tagline: Technology, Gaming and Development
description: >-
  Technology discussion, plenty of gaming and the few useful development tips and rants!
theme: jekyll-theme-midnight